trigger:
- main

pool:
  vmImage: 'windows-latest'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.x'

- script: dotnet restore
  displayName: 'Restore'

- script: dotnet build --configuration Release
  displayName: 'Build'

- script: dotnet test --configuration Release --collect:"XPlat Code Coverage"
  displayName: 'Test'

- task: PublishCodeCoverageResults@2
  inputs:
    codeCoverageTool: 'Cobertura'
    summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/coverage.cobertura.xml'

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: true
    arguments: '--configuration Release --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: true

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'drop'

- task: AzureWebApp@1
  inputs:
    azureSubscription: '<YOUR-SERVICE-CONNECTION>'
    appName: '<YOUR-APP-SERVICE-NAME>'
    package: '$(Build.ArtifactStagingDirectory)/**/*.zip'
