#services:
#  sampleapi:
#    image: ${DOCKER_REGISTRY-}sampleapi
#    build:
#      context: .
#      dockerfile: SampleApi/Dockerfile

version: '3.8'

services:
  sampleapi:
    container_name: sampleapi
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      ConnectionStrings__DefaultConnection: ${ConnectionStrings__DefaultConnection}
      Jwt__Key: ${Jwt__Key}
      Jwt__Issuer: ${Jwt__Issuer}
      Jwt__Audience: ${Jwt__Audience}
      ASPNETCORE_ENVIRONMENT: "Development"

