#services:
#  sampleapi:
#    environment:
#      - ASPNETCORE_ENVIRONMENT=Development
#      - ASPNETCORE_HTTP_PORTS=8080
#     - ASPNETCORE_HTTPS_PORTS=8081
#    ports:
#      - "8080"
#      - "8081"
#    volumes:
#      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
#      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
#      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
#      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

#only used by Visual Studio
version: '3.8'

services:
  sampleapi:
    environment:
      ASPNETCORE_ENVIRONMENT: "Development" 
    volumes: #this avoids restoring the nuget packages, specially the SqlClient (EF), because in open networks these packages are big and cannot be restored
      - C:\Users\mark_\.nuget\packages:/root/.nuget/packages:ro