name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore SampleApi.sln

    - name: Build solution
      run: dotnet build SampleApi.sln --configuration Release --no-restore

    - name: Run tests
      run: dotnet test SampleApi.Test/SampleApi.Test.csproj --no-build --verbosity normal
    
    - name: Run tests
      run: dotnet test SampleApi.Test/bin/Debug/net8.0/SampleApi.Test.dll



