- name: Run VSTest with coverage
  run: dotnet msbuild SampleApi.Test/SampleApi.Test.csproj /t:VSTest /p:Configuration=Release /p:VSTestCollect="XPlat Code Coverage"

- name: Upload coverage report
  uses: actions/upload-artifact@v4
  with:
    name: coverage
    path: SampleApi.Test/TestResults/
